Webin_cli API Docs
enasequence/ena-browser-documentation pull request #20
Opened 2021-08-05 15:38 UTC by ahmadazd

This is the documentation for the Webin-cli SARS-COV-2 genome submission API to be included within the SARS-COV-2 readthedoc.

2021-08-09 10:16 UTC, carlacummins commented on help_and_guides/Webin-Cli_SARS-CoV-2_Genome_Submission_REST_API.md
> +        data=sample_json, auth=('Webin-56388', 'IlR07wf18uaE')
```suggestion
        data=sample_json, auth=('Webin-XXXXXX', 'password')
```

2021-08-10 08:06 UTC, raskoleinonen requested changes
- Suggested several changes. Please see branch raskoleinonen-patch-1.

2021-08-10 12:10 UTC, raskoleinonen approved these changes

2021-08-11 16:37 UTC, nadimm-rahman requested changes
Recommending addition of a link to the SARS-CoV-2 submission instructions. We should also add a link to this page from the SARS-CoV-2 submission instructions page.

2021-08-11 16:37 UTC, nadimm-rahman commented on help_and_guides/Webin-Cli_SARS-CoV-2_Genome_Submission_REST_API.md
> +Webin SARS-CoV-2 Genome Submission Web API is a JSON based service used to submit SARS-CoV-2 genome assemblies to the European Nucleotide Archive (ENA).
```suggestion
Webin SARS-CoV-2 Genome Submission Web API is a JSON based service used to submit SARS-CoV-2 genome assemblies to the European Nucleotide Archive (ENA). For further information on submitting SARS-CoV-2 genomes, see our [SARS-CoV-2 Submission Instructions](https://ena-browser-docs.readthedocs.io/en/latest/help_and_guides/sars-cov-2-submissions.html#submitting-assemblies).
```

2021-08-12 14:53 UTC, merged